version: '3'

services:
  hackernews-telegram-bot:
    build: .
    volumes:
        - data-volume:/usr/src/app/data
    environment:
        - DEBUG=*
    command: bash -c "node bot.js 2> /tmp/error.log > /tmp/log.log"

volumes:
  data-volume:
