version: '3'

services:
  hackernews-telegram-bot:
    build: .
    volumes:
        - './users_data:/usr/src/app/data'
        - './logs:/usr/src/app/logs'
        - './news_data:/usr/src/app/news_data'
    environment:
        - DEBUG=*,-node-telegram-bot-api
    command: bash -c "node bot.js 2> /usr/src/app/logs/error.log > /usr/src/app/logs/log.log"
